# Generated by Django 5.2.5 on 2025-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('TQ', 'Technique'), ('BK', 'Book'), ('FR', 'Furniture'), ('SP', 'Sport'), ('CN', 'Children'), ('DF', 'Default')], default='DF')),
                ('rating', models.FloatField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('count_items', models.IntegerField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
