# Generated by Django 5.2.5 on 2025-08-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_feedback_description_alter_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
